CloudKitchen/CloudKitchen/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
]

CloudKitchen/Home/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.homepage, name="Home"),
    path('contact/', views.contact, name="ContactUs"),
    path('about/', views.about, name="About"),
    path('partner/', views.partner, name="Partner"),
    path('register/', views.register, name="Register"),
    path('login/', views.login, name="Login"),
    path('forgot/', views.forgot, name="Forgot"),
    path('verify/', views.verify, name="Verify"),
    path('reset/', views.reset, name="Reset"),
    path('user/', include('User.urls')),
    path('restaurantLogin/', views.restaurantLogin, name="RestaurantLogin"),
    path('restaurantForgot/', views.restaurantForgot, name="RestaurantForgot"),
    path('restaurantVerify/', views.restaurantVerify, name="RestaurantVerify"),
    path('restaurantReset/', views.restaurantReset, name="RestaurantReset"),
    path('restaurant/', include('Restaurant.urls')),
    path('deliveryLogin/', views.deliveryLogin, name="DeliveryLogin"),
    path('deliveryForgot/', views.deliveryForgot, name="DeliveryForgot"),
    path('deliveryVerify/', views.deliveryVerify, name="DeliveryVerify"),
    path('deliveryReset/', views.deliveryReset, name="DeliveryReset"),
    path('delivery/', include('Delivery.urls')),
    path('browseRestaurants/', views.browseRestaurant, name="BrowseRestaurants"),
    path('browseRestaurants/<str:id>', views.restaurantMenu, name="RestaurantMenu"),
]

CloudKitchen/Restaurant/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.homepage, name="Home"),
    path('contact/', views.contact, name="Contact"),
    path('about/', views.about, name="About"),
    path('viewProfile/', views.viewProfile, name="ViewProfile"),
    path('resetPassword/', views.resetPassword, name="ResetPassword"),
    path('updateProfile/', views.updateProfile, name="UpdateProfile"),
    path('open/<str:image>', views.download_image, name="DownloadImage"),
    path('logout/', views.logout, name="LogOut"),
    path('menu/', views.menu, name="Menu"),
    path('addCategory/', views.addCategory, name="AddCategory"),
    path('addCategoryItem/', views.addCategoryItem, name="AddCategoryItem"),
    path('addItem/<str:category>', views.addItem, name="AddItem"),
    path('deleteCategory/<str:category>', views.deleteCategory, name="DeleteCategory"),
    path('deleteItem/<str:category>/<str:item>', views.deleteItem, name="DeleteItem"),
    path('updateCategory/<str:category>', views.updateCategory, name="UpdateCategory"),
    path('updateItem/<str:category>/<str:item>', views.updateItem, name="UpdateItem"),
    path('order/', views.order, name="Order"),
    path('updateOrder/', views.updateOrder, name="UpdateOrder"),
    path('orderHistory/', views.orderHistory, name="OrderHistory"),
]

CloudKitchen/Restaurant/models.py
from django.db import models
from Home.models import Restaurant, User, Delivery
from User.models import Address

class Query(models.Model):
    name = models.CharField(max_length=100)
    email = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    subject = models.CharField(max_length=50)
    message = models.CharField(max_length=1000)

class Category(models.Model):
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    category = models.CharField(max_length=50)

    class Meta:
        unique_together = (("restaurant", "category"))

    def __unicode__(self):
        return u'%s' % (self.category)

class Item(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    quantity = models.CharField(max_length=100)
    item_type = models.CharField(max_length=7)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    count = models.IntegerField(default=0)

class Orders(models.Model):
    order_number = models.IntegerField(primary_key=True)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    address = models.ForeignKey(Address, on_delete=models.CASCADE)
    items = models.CharField(max_length=500)
    quantity = models.CharField(max_length=50)
    total = models.DecimalField(max_digits=10, decimal_places=2)
    delivery = models.CharField(max_length=6, blank=True, null=True)
    accepted = models.BooleanField(default=False)
    food_is_being_prepared = models.BooleanField(default=False)
    ready_for_delivery = models.BooleanField(default=False)
    picked_up = models.BooleanField(default=False)
    out_for_delivery = models.BooleanField(default=False)
    delivered = models.BooleanField(default=False)
    date = models.DateField(default="2020-01-01")
    time = models.TimeField(default="00:00:00")

class Feedback(models.Model):
    order = models.ForeignKey(Orders, unique=True, on_delete=models.CASCADE)
    food_quality = models.CharField(max_length=15)
    order_accuracy = models.CharField(max_length=15)
    packaging = models.CharField(max_length=15)
    feedback = models.CharField(max_length=500)

CloudKitchen/Home/forms.py
from django import forms
from .models import User

class RegisterForm(forms.Form):
    name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'size':100, 'class': 'form-control', 'placeholder': 'Full Name'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email Address'}))
    contact = forms.IntegerField(widget=forms.NumberInput(attrs={'min':6000000000, 'max':9999999999, 'class': 'form-control', 'placeholder': 'Contact Number'}))
    password = forms.CharField(max_length=10, min_length=8, widget=forms.PasswordInput(attrs={'size':10, 'class': 'form-control', 'placeholder': 'Password'}))
    re_password = forms.CharField(max_length=10, min_length=8, widget=forms.PasswordInput(attrs={'size':10, 'class': 'form-control', 'placeholder': 'Repeat Password'}))

    def clean(self):
        cd = self.cleaned_data
        if User.objects.filter(email=cd.get("email")).exists():
            raise forms.ValidationError("A user account with the given email address exists.\\nTry another email address.")
        if User.objects.filter(contact=cd.get("contact")).exists():
            raise forms.ValidationError("A user account with the given email contact number exists.\\nTry another contact number.")

class LoginForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email Address'}))
    password = forms.CharField(max_length=10, min_length=8, widget=forms.PasswordInput(attrs={'size': 10, 'class': 'form-control', 'placeholder': 'Password'}))

class ForgotForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email Address'}))

class ResetForm(forms.Form):
    password = forms.CharField(max_length=10, min_length=8, widget=forms.PasswordInput(attrs={'size': 10, 'class': 'form-control', 'placeholder': 'New Password'}))
    re_password = forms.CharField(max_length=10, min_length=8, widget=forms.PasswordInput(attrs={'size': 10, 'class': 'form-control', 'placeholder': 'Repeat New Password'}))

class ContactUsForm(forms.Form):
    name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'size': 100, 'class': 'common-input mb-20 form-control', 'placeholder': 'Enter Your Name'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'common-input mb-20 form-control', 'placeholder': 'Enter Email Address'}))
    subject = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'size': 50, 'class': 'common-input mb-20 form-control', 'placeholder': 'Enter Subject'}))
    message = forms.CharField(max_length=1000, min_length=50, widget=forms.Textarea(attrs={'size': 10, 'class': 'common-textarea form-control', 'placeholder': 'Enter Query', 'style': 'height: 202px;'}))

cuisines = (('North Indian', 'North Indian'), ('South Indian', 'South Indian'), ('Fast Food', 'Fast Food'), ('Beverages', 'Beverages'), ('Bakery', 'Bakery'), ('Desserts', 'Desserts'), ('Italian', 'Italian'), ('Chinese', 'Chinese'))
days = (('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday'))

class PartnerForm(forms.Form):
    restaurant_name = forms.CharField(max_length=100, error_messages={'required':"Please Enter your Name"}, widget=forms.TextInput(attrs={'size': 100, 'class': 'form-control', 'placeholder': 'Restaurant Name'}))
    owner_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'size': 100, 'class': 'input-text', 'placeholder': 'Owner Name'}))
    address = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'size': 100, 'class': 'input-text', 'placeholder': 'Address / Locality'}))
    city = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'size': 20, 'class': 'input-text', 'placeholder': 'City'}))
    zip = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'input-text', 'placeholder': 'Zip Code'}))
    restaurant_email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'input-text', 'placeholder': 'Restaurant Email Address'}))
    restaurant_contact = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'input-text', 'placeholder': 'Restaurant Contact Number'}))
    password = forms.CharField(max_length=10, widget=forms.PasswordInput(attrs={'size': 10, 'class': 'input-text', 'placeholder': 'Password'}))
    cost_for_two = forms.DecimalField(widget=forms.NumberInput(attrs={'class': 'input-text', 'placeholder': 'Cost for Two'}))
    outlets = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'input-text', 'placeholder': 'Number of Outlets'}))
    cuisine = forms.MultipleChoiceField(required=True, choices=cuisines, widget=forms.CheckboxSelectMultiple())
    working_days =forms.MultipleChoiceField(required=True, choices=days, widget=forms.CheckboxSelectMultiple())
    shop_license = forms.FileField(widget=forms.FileInput(attrs={'class': 'input-text', 'accept': '.pdf'}))
    fssai = forms.FileField(widget=forms.FileInput(attrs={'class': 'input-text', 'accept': '.pdf'}))
    gstin_pan = forms.FileField(widget=forms.FileInput(attrs={'class': 'input-text', 'accept': '.pdf'}))
    menu = forms.FileField(widget=forms.FileInput(attrs={'class': 'input-text', 'accept': '.pdf'}))
    facade = forms.ImageField(widget=forms.ClearableFileInput(attrs={'class': 'form-control'}))
    kitchen = forms.ImageField(widget=forms.ClearableFileInput(attrs={'class': 'form-control'}))
    dining_packaging = forms.ImageField(widget=forms.ClearableFileInput(attrs={'class': 'form-control'}))
    locality = forms.ImageField(widget=forms.ClearableFileInput(attrs={'class': 'form-control'}))

class RestaurantLoginForm(forms.Form):
    restaurant_id = forms.CharField(max_length=6, widget=forms.TextInput(attrs={'size':6, 'class': 'form-control', 'placeholder': 'Restaurant ID'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email Address'}))
    password = forms.CharField(max_length=10, min_length=8, widget=forms.PasswordInput(attrs={'size': 10, 'class': 'form-control', 'placeholder': 'Password'}))

class DeliveryLoginForm(forms.Form):
    id = forms.CharField(max_length=6, min_length=6, widget=forms.TextInput(attrs={'size': 8, 'class': 'form-control', 'placeholder': 'Delivery Person ID'}))
    password = forms.CharField(max_length=10, min_length=8, widget=forms.PasswordInput(attrs={'size': 10, 'class': 'form-control', 'placeholder': 'Password'}))

CloudKitchen/Restaurant/forms.py
from django import forms

class ContactUsForm(forms.Form):
    name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'size': 100, 'class': 'common-input mb-20 form-control', 'placeholder': 'Enter Your Name', 'readonly':'readonly'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'common-input mb-20 form-control', 'placeholder': 'Enter Email Address', 'readonly':'readonly'}))
    subject = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'size': 50, 'class': 'common-input mb-20 form-control', 'placeholder': 'Enter Subject'}))
    message = forms.CharField(max_length=1000, min_length=50, widget=forms.Textarea(attrs={'size': 10, 'class': 'common-textarea form-control', 'placeholder': 'Enter Query', 'style': 'height: 202px;'}))

class CategoryForm(forms.Form):
    category = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'size': 50, 'class': 'input--style-1', 'placeholder': 'Category Name'}))

class CategoryItemForm(forms.Form):
    category = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'size': 50, 'class': 'input--style-1', 'placeholder': 'Category Name', 'readonly':'readonly'}))
    item = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'size': 50, 'class': 'input--style-1', 'placeholder': 'Item Name'}))
    price = forms.DecimalField(widget=forms.NumberInput(attrs={'class': 'input--style-1', 'placeholder': 'Price'}))

class ResetPasswordForm(forms.Form):
    old_password = forms.CharField(max_length=10, min_length=8, widget=forms.PasswordInput(attrs={'size': 10, 'class': 'form-control', 'placeholder': 'Old Password'}))
    password = forms.CharField(max_length=10, min_length=8, widget=forms.PasswordInput(attrs={'size': 10, 'class': 'form-control', 'placeholder': 'New Password'}))
    re_password = forms.CharField(max_length=10, min_length=8, widget=forms.PasswordInput(attrs={'size': 10, 'class': 'form-control', 'placeholder': 'Repeat New Password'}))

cuisines = (('North Indian', 'North Indian'), ('South Indian', 'South Indian'), ('Fast Food', 'Fast Food'), ('Beverages', 'Beverages'), ('Bakery', 'Bakery'), ('Desserts', 'Desserts'), ('Italian', 'Italian'), ('Chinese', 'Chinese'))
days = (('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday'))

class UpdateProfileForm(forms.Form):
    owner_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'size': 100, 'class': 'input-text', 'placeholder': 'Owner Name'}))
    address = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'size': 100, 'class': 'input-text', 'placeholder': 'Address / Locality'}))
    city = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'size': 20, 'class': 'input-text', 'placeholder': 'City'}))
    zip = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'input-text', 'placeholder': 'Zip Code'}))
    restaurant_contact = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'input-text', 'placeholder': 'Restaurant Contact Number'}))
    cost_for_two = forms.DecimalField(widget=forms.NumberInput(attrs={'class': 'input-text', 'placeholder': 'Cost for Two'}))
    outlets = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'input-text', 'placeholder': 'Number of Outlets'}))

CloudKitchen/Restaurant/templates/addCategory.html
{% extends "restaurantBase.html" %}

{% load static %}

{% block head %}

<link rel="stylesheet" type="text/css" href="{% static 'css/menu.css' %}">
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<link href="{% static 'vendor/mdi-font/css/material-design-iconic-font.min.css' %}" rel="stylesheet" media="all">
<link href="{% static 'vendor/font-awesome-4.7/css/font-awesome.min.css' %}" rel="stylesheet" media="all">

<link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i" rel="stylesheet">

<link href="{% static 'vendor/select2/select2.min.css' %}" rel="stylesheet" media="all">
<link href="{% static 'vendor/datepicker/daterangepicker.css' %}" rel="stylesheet" media="all">

<link href="{% static 'css/main.css' %}" rel="stylesheet" media="all">

{% endblock %}

{% block title %} Restaurant | Add Category {% endblock %}

{% block menu %} active {% endblock %}

{% block content %}

{% if messages %}
    {% for message in messages %}
        <script>alert("{{ message }}")</script>
    {% endfor %}
{% endif %}

<img src="{% static 'img/addCategory.jpg' %}" class="banner">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">

<div class="page-wrapper bg-blue p-t-100 p-b-100 font-robo">
    <div class="wrapper wrapper--w680">
        <div class="card card-1">
            <div class="card-heading"></div>
            <div class="card-body">
                <h2 class="title" align="center">Category</h2>
                <form action="{% url 'AddCategoryItem' %}" method="get">
                    {% csrf_token %}
                    <div class="input-group">
                        {{ form.category }}
                    </div>
                    <div class="p-t-20" align="center">
                        <button class="btn btn--radius btn--green" type="submit">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>

<script src="{% static 'vendor/select2/select2.min.js' %}"></script>
<script src="{% static 'vendor/datepicker/moment.min.js' %}"></script>
<script src="{% static 'vendor/datepicker/daterangepicker.js' %}"></script>

<script src="{% static 'js/global.js' %}"></script>

{% endblock %}

CloudKitchen/Restaurant/templates/resetPassword.html
{% extends "restaurantBase.html" %}

{% load static %}

{% block head %}

<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<script type="text/javascript" src="{% static 'js/register.js' %}"> </script>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>

{% endblock %}

{% block title %} Restaurant | Reset Password {% endblock %}

{% block content %}

{% if messages %}
    {% for message in messages %}
        <script>alert("{{ message }}")</script>
    {% endfor %}
{% endif %}

<img src="{% static 'img/resetPassword.jpg' %}" class="banner">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">

<div class="login-form">
    <form action="{% url 'ResetPassword' %}" method="post" onsubmit="return validate();">
        {% csrf_token %}
		<h3 align="center"><i class="fa fa-lock fa-4x"></i></h3>
        <h2 class="text-center">Reset Password</h2>
        <br>
        <div class="form-group input-group">
			<div class="input-group-prepend">
				<span class="input-group-text"> <i class="fa fa-lock fa-2x"></i> </span>
			</div>
			{{ form.old_password }}
		</div>
        <div class="form-group input-group">
			<div class="input-group-prepend">
				<span class="input-group-text"> <i class="fa fa-lock fa-2x"></i> </span>
			</div>
			{{ form.password }}
		</div>
		<div class="form-group input-group">
			<div class="input-group-prepend">
				<span class="input-group-text"> <i class="fa fa-lock fa-2x"></i> </span>
			</div>
			{{ form.re_password }}
		</div>
        <input type="submit" style="width: 100%;" class="btn btn-primary btn-block btn-lg" value="Submit">
    </form>
</div>

{% endblock %}

CloudKitchen/Restaurant/templates/updateProfile.html
{% extends "restaurantBase.html" %}

{% load static %}

{% block head %}

<link rel="stylesheet" type="text/css" href="{% static 'css/montserrat-font.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'fonts/material-design-iconic-font/css/material-design-iconic-font.min.css' %}">
<link rel="stylesheet" href="{% static 'css/newstyle1.css' %}"/>
<script type="text/javascript" src="{% static 'js/updateProfile.js' %}"> </script>

{% endblock %}

{% block title %} Restaurant | Update Profile {% endblock %}

{% block content %}

{% if messages %}
    {% for message in messages %}
        <script>alert("{{ message }}")</script>
    {% endfor %}
{% endif %}

<img src="{% static 'img/updateProfile.jpg' %}" class="banner">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">

<body class="form-v10">
	<div class="page-content">
		<div class="form-v10-content">
			<form class="form-detail" action="{% url 'UpdateProfile' %}" method="post" id="myform" onsubmit="return validate();">
				{% csrf_token %}
				<div class="form-left">
					<h2>Restaurant Details</h2>
					<div class="form-row">
						<input type="text" name="restaurant_id" class="form-control" placeholder="Restaurant ID" value="{{ obj.restaurant_id }}" readonly>
					</div>
					<div class="form-row">
						<input type="text" name="restaurant_name" class="form-control" placeholder="Restaurant Name" value="{{ obj.restaurant_name }}" readonly>
					</div>
					<div class="form-row">
						{{ form.owner_name }}
					</div>
					<div class="form-row">
						{{ form.address }}
					</div>
					<div class="form-group">
						<div class="form-row form-row-1">
							{{ form.city }}
						</div>
						<div class="form-row form-row-2">
							{{ form.zip }}
						</div>
					</div>
					<div class="form-row">
						<input type="email" name="restaurant_email" class="input-text" placeholder="Restaurant Email Address" value="{{ obj.restaurant_email }}" readonly>
					</div>
					<div class="form-row">
						{{ form.restaurant_contact }}
					</div>
					<div class="form-row" style="font-size: 15px;">
						<br>
						(<u>Note</u>: For updating the Images and Documents, kindly contact our team at cloudkitchen356@gmail.com)
					</div>
				</div>
				<div class="form-right">
					<h2>Detailed Information</h2>
					<div class="form-row">
						{{ form.cost_for_two }}
					</div>
					<div class="form-row">
						{{ form.outlets }}
					</div>
					<div class="form-right form-group">
						<div class="form-row form-row-1">
							<h4 style="color: white;">Cuisine</h4>
							<input type="hidden" name="cuisines" id="cuisines" value="">
							<ul id="id_cuisine">
								{% for mykey, myvalue in cuisine.items %}
									<li>
										{% if myvalue %}
											<input type="checkbox" name="cuisine" value="{{ mykey }}" checked> {{ mykey }}
										{% else %}
											<input type="checkbox" name="cuisine" value="{{ mykey }}"> {{ mykey }}
										{% endif %}
									</li>
								{% endfor %}
							</ul>
						</div>
						<div class="form-row form-row-2">
							<h4 style="color: white;">Working Days</h4>
							<input type="hidden" name="working_day" id="working_day" value="">
							<ul id="id_working_days">
								{% for mykey, myvalue in working_day.items %}
									<li>
										{% if myvalue %}
											<input type="checkbox" name="working_days" value="{{ mykey }}" checked> {{ mykey }}
										{% else %}
											<input type="checkbox" name="working_days" value="{{ mykey }}"> {{ mykey }}
										{% endif %}
									</li>
								{% endfor %}
							</ul>
						</div>
					</div>
					<div class="form-group">
						<div class="form-row form-row-1">
							<select name="from_time" class="input-from" id="from_time">
								{% for mykey, myvalue in times.items %}
									{% if mykey == obj.opening_time %}
										<option value="{{ mykey }}" disabled selected>{{ myvalue }}</option>
									{% else %}
										<option value="{{ mykey }}">{{ myvalue }}</option>
									{% endif %}
								{% endfor %}
							</select>
							<span class="select-btn">
							  	<i class="zmdi zmdi-chevron-down"></i>
							</span>
						</div>
						<div class="between" align="center">
							to
						</div>
						<div class="form-row form-row-2">
							<select name="to_time" class="input-from" id="to_time">
								{% for mykey, myvalue in times.items %}
									{% if mykey == obj.closing_time %}
										<option value="{{ mykey }}" disabled selected>{{ myvalue }}</option>
									{% else %}
										<option value="{{ mykey }}">{{ myvalue }}</option>
									{% endif %}
								{% endfor %}
							</select>
							<span class="select-btn">
							  	<i class="zmdi zmdi-chevron-down"></i>
							</span>
						</div>
					</div>
					<div class="form-row-last">
						<a href="/restaurant/updateProfile"><input type="submit" name="register" class="register" value="Update"></a>
					</div>
				</div>
			</form>
		</div>
	</div>
</body>

{% endblock %}